# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('is_product', models.BooleanField()),
                ('is_store', models.BooleanField()),
                ('is_correct', models.BooleanField(default=True)),
                ('is_to_update', models.BooleanField(default=False)),
            ],
        ),
    ]
